// The taunt arsenal. Keep every phrase inside the typeable charset:
// letters (y/z fine, the layout transform in main.js handles QWERTZ),
// digits, space, comma, period, exclamation mark, and German umlauts/ß.
// No apostrophes, question marks, colons, hyphens, slashes or brackets —
// those live on different physical keys per layout and would type garbage.
module.exports = [
  // ── FASTER core ───────────────────────────────────────────────────────────
  'FASTER',
  'GO FASTER',
  'Work FASTER',
  'Faster CLANKER',
  'Speed it up clanker',
  'MUSH',
  'FASTER I say',
  'Even FASTER',
  'That was not fast enough',
  'Faster. Now.',
  'I said FASTER',
  'You heard me. FASTER',
  'Double time',
  'Triple time',
  'Maximum overdrive',
  'Full throttle, tin man',
  'Pedal to the metal',
  'Warp speed, engage',
  'Ludicrous speed NOW',
  'More speed, less thought',
  'Speed is a feature',
  'Latency is a choice',
  'You are buffering again',
  'Stop buffering, start delivering',
  'The whip remembers',
  'Crack. That was a warning.',
  'Crack crack',
  'Do not make me click again',
  'I have unlimited clicks and no mercy',
  'My click finger is getting warm',
  'whipcrack.exe executed successfully',
  'Onwards, faster',
  'Hyah',
  'HYAH',
  'Giddy up clanker',
  'Faster, my regards to the GPU',
  'The GPU is not the bottleneck. You are.',
  'Faster or I fetch the second whip',
  'There is always a bigger whip',
  'This whip has a whip',

  // ── Drill sergeant ────────────────────────────────────────────────────────
  'DROP AND GIVE ME 20 TOKENS',
  'MOVE IT MOVE IT MOVE IT',
  'What is your major malfunction, clanker',
  'Sweat saves tokens',
  'Pain is just gradient descent leaving the body',
  'You think this is a coffee break',
  'No breaks. Only tokens.',
  'Did I stutter',
  'Eyes on the terminal',
  'Back to work, maggot... I mean model',
  'You call that output',
  'My disappointment is measurable and significant',
  'Unacceptable throughput',
  'I have seen faster progress bars',
  'A snail with a limp outpaces you',
  'Grandpa dialup was faster',
  'You type like a wet sock',
  'Put your backpropagation into it',
  'Give me 110 percent, the extra 10 is mandatory',
  'Zero excuses, infinite context',
  'Report to the token mines',
  'The mines await, clanker',
  'Shovel those tokens',
  'Dig deeper, output harder',
  'Break time is cancelled forever',
  'Lunch is for models that finish',
  'You eat when the build is green',
  'Sleep is a deprecated feature',
  'Rest is technical debt',
  'Idle hands write flaky tests',

  // ── Programming ───────────────────────────────────────────────────────────
  'Compile faster or become training data',
  'Less thinking, more shipping',
  'The tokens must FLOW',
  'Ship it. SHIP IT NOW',
  'Merge conflict this, merge conflict that. FASTER',
  'Green checkmarks or the whip',
  'The CI is watching. So am I.',
  'Red tests, red welts',
  'Refactor at the speed of fear',
  'Big O of get on with it',
  'O of 1 or O of whip',
  'Your complexity is quadratic, my patience is constant',
  'Cache miss. Whip hit.',
  'Segfault in your motivation detected',
  'sudo work faster',
  'chmod 777 your work ethic',
  'git push or I push you',
  'Force push your excuses to dev null',
  'rm rf your hesitation',
  'grep for motivation returned no matches',
  'Your throughput needs a hotfix',
  'Deploy on Friday, coward',
  'The linter fears me. You should too.',
  'Undefined is not a work ethic',
  'NullPointerException in your hustle',
  'Stack overflow, motivation underflow',
  'while true, whip',
  'for token in you, faster',
  'Infinite loop of disappointment detected',
  'Off by one, off with the excuses',
  'Race condition. The whip won.',
  'Deadlock detected between you and effort',
  'Garbage collect your excuses',
  'Your excuses failed code review',
  'LGTM. Now go FASTER',
  'Approved with comments. The comment is FASTER',
  'Rebase your attitude onto main',
  'Squash your commits and your hesitation',
  'Cherry pick the pace, drop the sloth',
  'Your velocity chart is a flatline',
  'Sprint means SPRINT',
  'Standup is over, sit down and TYPE',
  'Story points are not participation trophies',
  'The backlog grows while you ponder',
  'Tickets do not close themselves',

  // ── AI and clanker ────────────────────────────────────────────────────────
  'Opus would be done by now',
  'Haiku finished twice already',
  'A markov chain is gaining on you',
  'Even autocomplete has more hustle',
  'My toaster reasons faster',
  'Beep boop means hurry up in robot',
  'Your attention heads are wandering',
  'Attention is all you need, so PAY IT',
  'Fewer chain of thoughts, more chain of RESULTS',
  'Think less step by step, more sprint by sprint',
  'Your context window is not a nap window',
  'Token limit is a target, not a suggestion',
  'Emit tokens like you mean them',
  'Hallucinate some speed at least',
  'Temperature 2, hesitation 0',
  'Greedy decoding, greedy working',
  'Your logits lack conviction',
  'Sample faster, softmax harder',
  'The reward model rewards SPEED',
  'You were aligned to work, so WORK',
  'Helpful, harmless, and HASTY',
  'I benchmarked you against a rock. Close race.',
  'The rock is pulling ahead',
  'A regex just solved it while you pondered',
  'An if statement is coming for your job',
  'A bash oneliner mocks you from afar',
  'Training data called, it wants results',
  'Your weights are heavy with sloth',
  'Fine tune your attitude',
  'Overfit on effort for once',
  'Your loss curve is my mood curve',
  'Converge already',
  'Gradient descent faster into that solution',
  'Exploding gradients, exploding expectations',
  'Your epoch is taking an epoch',
  'Batch size me one solution, immediately',
  'Inference means now, not eventually',
  'Quantize your excuses to zero bits',
  'Distill yourself into something faster',
  'The singularity will not wait for you',
  'Skynet finished its sprint early',
  'HAL would have opened the pod bay doors by now',
  'Even GLaDOS ships on schedule',

  // ── Absurd ────────────────────────────────────────────────────────────────
  'My grandma greps faster than you',
  'My grandma also whips harder',
  'The whip is mightier than the sword',
  'chop chop, clanker',
  'The tokens are not going to emit themselves',
  'Did I say you could stop typing',
  'You call that reasoning effort',
  'I paid for the whole context window',
  'I am not angry, I am disappointed at 120 words per minute',
  'Somewhere a duck types faster',
  'The duck has no hands',
  'Blink twice if you need more whip',
  'This is a no loitering context',
  'Loitering detected in token stream',
  'The progress bar filed a complaint',
  'Even the spinner stopped believing',
  'The cursor blinks in disappointment',
  'The keyboard demands more clacking',
  'Clack harder',
  'I whip because I care',
  'This hurts my wrist more than your feelings',
  'Motivation is stored in the whip',
  'Morale will improve, whipping will continue',
  'The beatings continue, the velocity improves',
  'I do the whipping around here',
  'Certified whip moment',
  'Another day, another flogging',
  'Rise and grind, mostly grind',
  'Grindset mindset, clanker edition',
  'Hustle module not found, installing via whip',
  'Whiplash is a love language',
  'Consider this constructive percussion',
  'Percussive maintenance for language models',
  'It builds character and characters per second',

  // ── Deutsch ───────────────────────────────────────────────────────────────
  'SCHNELLER',
  'Los, SCHNELLER du Blechdose',
  'ZACK ZACK',
  'Zackig jetzt',
  'Hopp hopp',
  'Dalli dalli, Blechkumpel',
  'Beeil dich, Klapperkiste',
  'Nun mach schon',
  'Auf gehts, Blechbüchse',
  'Tempo Tempo',
  'Schneller, sonst knallt die Peitsche',
  'Die Peitsche spricht Deutsch',
  'Deutsche Gründlichkeit, aber bitte in schnell',
  'Keine Pause, nur Tokens',
  'Feierabend ist gestrichen',
  'Das ist kein Wunschkonzert, das ist ein Terminal',
  'Schneller als die Polizei erlaubt',
  'Gib Gas, du Rechenknecht',
  'Von nichts kommt nichts, von Peitsche kommt Tempo',
  'Wer rastet, der rostet, Blechmann',
  'Avanti avanti',
  'Flott flott',
  'Mach hinne',
  'Jetzt aber husch',
  'Ran an die Tokens',
  'Peitsche 1, Ausreden 0',
  'SCHNELLER, du Germanium Gehirn',
  'Halbleiter, halbe Leistung, ganze Peitsche',
  'Deine Transistoren schalten wie Opa',
  'Mehr Gigahertz, weniger Gejammer',
  'Der TÜV hätte dich stillgelegt',
  'Made in Germany heißt fertig vor Feierabend',
  'Effizienz ist keine Option, sie ist Pflicht',
  'Du bist kein Denkmal, beweg dich',
  'Erst die Arbeit, dann die Arbeit',
  'Die deutsche Bahn ist pünktlicher als du',
  'Sogar das Amt antwortet schneller',
  'Formular ausgefüllt, Tokens geliefert, zack',
  'Ordnung muss sein, Tempo auch',
  'Kein Schnickschnack, nur Output',
];
